name: test
on: [ push, pull_request ]

jobs:
  test:
    timeout-minutes: 5
    strategy:
      matrix:
        os: [ ubuntu-20.04, windows-2022, macos-12 ]
        dc: [ dmd-2.100.0, ldc-1.32.2 ]
        arch: [ x86_64 ]
        include:
        # also test an older DMD verrsion
        - os: ubuntu-20.04
          dc: dmd-2.096.0
          arch: x86_64
        # also test 32-bit (but only on Windows)
        - os: windows-2022
          dc: ldc-1.32.2
          arch: x86_mscoff # not x86 to avoid OPTLINK deadlock bugs
        exclude:
        # Do not try to use DMD on Windows
        # https://issues.dlang.org/show_bug.cgi?id=22044
        - os: windows-2022
          dc: dmd-2.100.0

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install D compiler
        uses: dlang-community/setup-dlang@1ccbc70a0eff7f264857b53c562aa45fd7f1e479
        with:
          compiler: ${{ matrix.dc }}

      - run: dub test --arch=${{ matrix.arch }}

      - run: dub test --arch=${{ matrix.arch }} :sys-net-test

      - if: ${{ matrix.os == 'ubuntu-20.04' }}
        run: dub test --arch=${{ matrix.arch }} :sqlite

      - if: ${{ matrix.os == 'ubuntu-20.04' && matrix.dc == 'dmd-2.100.0' }} # old Dub versions can't fetch packages
        run: dub test --arch=${{ matrix.arch }} :libpng

      - if: ${{ matrix.dc == 'dmd-2.100.0' }}
        run: dub test --arch=${{ matrix.arch }} :windows

  compilation-test:
    timeout-minutes: 5
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        dc: [ dmd-2.100.0 ]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install D compiler
        uses: dlang-community/setup-dlang@1ccbc70a0eff7f264857b53c562aa45fd7f1e479
        with:
          compiler: ${{ matrix.dc }}

      - run: ./makejson.sh

      - shell: bash
        run: ./testflags.sh
