name: test
on: [ push, pull_request ]
jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-20.04, windows-2019 ]
        dc: [ dmd-2.082.1 ]
        arch: [ x86_64 ]
        include:
        # also test x86 (but only on Windows)
        - os: windows-2019
          dc: dmd-2.082.1
          arch: x86
        # macos-10.15 needs DMD 2.087.1 or later:
        # https://github.com/dlang/druntime/commit/d4ff1c448d78dca14775571033fc7e583f904aa0
        - os: macos-10.15
          dc: dmd-2.088.0
          arch: x86_64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}
      - run: dub test --arch=${{ matrix.arch }}
      - if: ${{ matrix.os != 'windows-2019' }} # https://github.com/dlang-community/setup-dlang/issues/47
        run: dub test --arch=${{ matrix.arch }} ae:sys-net-test
